app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::auth();

Route::group(['middleware' => 'web'], function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::resource('song', 'SongController');

});

app/Song.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Song extends Model
{
    protected $table = 'songs';

    protected $fillable = [
      'judul', 'ekstensi', 'nama_default',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SongController.php
<?php

namespace App\Http\Controllers;

use App\Song;
use Illuminate\Http\Request;

use Validator;
use Session;
use App\Http\Requests;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;

class SongController extends Controller
{
    protected $songs;

    public function __construct(Song $songs)
    {
        $this->middleware('auth');

        $this->songs = $songs;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $songs = DB::table('songs')->paginate(5);

        return view('songs.index', compact('songs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Song $songs)
    {
        return view('songs.form', compact('songs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\StoreRequestSong $request)
    {
      $data = $request->all();

      if ($request->hasFile('nama_default')) {

          $video = $request->file('nama_default');
          $jalur = './songs';
          $namaVideo = $video->getClientOriginalName();
          $ekstensi = $video->getClientOriginalExtension();
          $namaBaruVideo = rand(11111,99999).$namaVideo;

          if ($ekstensi == 'mp4') {

              $upload = $request->file('nama_default')->move($jalur, $namaBaruVideo);

              if ($upload) {

                  $data['nama_default'] = $namaBaruVideo;

                  $this->songs->create($data);
                  return redirect(route('song.index'))->with('status', 'Video Berhasil Di Upload.');
              }
          }
          else {
            return redirect(route('song.index'))->with('status', 'Video Gagal Di Upload, Pastikan extensi video mp4.');
          }
      }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $songs = DB::table('songs')->findOrFail($id);
        $songs = $this->songs->findOrFail($id);
        $song = DB::table('songs')->paginate(5);

        return view('songs.play', compact('songs', 'song'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Lunavizta Karaoke Online</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Lunavizta Karaoke Online
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li class="@yield('active1')"><a href="{{ route('song.index')  }}">All Song</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                       <!-- <li><a href="{{ url('/register') }}">Register</a></li> -->
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @if($errors->any())
            <div class="alert alert-danger">
                <strong>Ditemukan kesalahan!</strong>
                <ul>
                    @foreach($errors->all() as $kesalahan)
                        <li>{{ $kesalahan  }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @if(session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif

            @yield('content')
    </div>

    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
</body>
</html>

resources/views/songs/form.blade.php
@extends('layouts.app')
@section('active1', 'active')
@section('content')
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Add New Song</div>
                    <div class="panel panel-body">
                        {!! Form::model($songs, [
                           'method' => $songs->exists ? 'put' : 'post', 'files' => true,
                           'route' => $songs->exists ? ['song.update', $songs->id] : ['song.store']
                        ]) !!}

                        <div class="form-group">
                            {!! Form::label('Judul Lagu') !!}
                            {!! Form::text('judul', null, ['class' => 'form-control required']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('Lagu') !!}
                            {!! Form::file('nama_default', ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="panel-footer">
                        {!! Form::submit($songs->exists ? 'Update' : 'Save', ['class' => 'btn btn-primary']) !!}
                        <a class="btn btn-default" href="{{ route('song.index')  }}">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/songs/index.blade.php
@extends('layouts.app')
@section('active1', 'active')
@section('content')
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">All Song</div>
                        <div class="panel panel-body">
                        </div>
                        <ul class="list-group">
                            @if($songs->isEmpty())
                                <button type="button" class="list-group-item">
                                    <p align="center">Nothing!</p>
                                </button>
                            @else
                                @foreach($songs as $song)
                                  <a href="{{ route('song.show', $song->id) }}" class="list-group-item">
                                    {{-- <span class="badge"><i class="fa fa-trash"></i></span> --}}
                                    <i class="fa fa-music"> {{ $song->judul_lagu  }}</i></a>
                                @endforeach
                            @endif
                        </ul>
                    {{-- <div class="panel-footer"></div> --}}
                </div>
                {!! $songs->render() !!}
            </div>
        </div>
@endsection

resources/views/songs/play.blade.php
@extends('layouts.app')
@section('active1', 'active')
@section('content')
    <div class="row">
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-music"> {{$songs->judul_lagu}}</i></div>
                    <div class="panel-body">
                        <div class="embed-responsive embed-responsive-16by9">
                            <video class="embed-responsive-item" controls>
                                <source src="{{ asset('songs/'.$songs->path) }}">
                            </video>
                        </div>
                    </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">Songs</div>
                <ul class="list-group">
                      @foreach($song as $songs)
                        <a href="{{ route('song.show', $songs->id) }}" class="list-group-item">
                          {{-- <span class="badge"><i class="fa fa-trash"></i></span> --}}
                          <i class="fa fa-music"> {{ $songs->judul_lagu  }}</i></a>
                      @endforeach
                </ul>
            </div>
            {!! $song->render() !!}
        </div>
    </div>
@endsection